#!/usr/bin/python3

import sys
import parsing
import client


def main():
    args = parsing.check_params(sys.argv)
    drone = client.Drone(args[0], args[2], args[1])
    drone.run()


if __name__ == "__main__":
    main()
